#stage 1
#Start with a base image containing Java runtime
FROM eclipse-temurin:21 AS build

# Add Maintainer Info
LABEL maintainer="Illary Huaylupo <illaryhs@gmail.com>"

# The application's jar file
#ARG JAR_FILE

# Add the application's jar to the container
COPY target/*.jar app.jar

#unpackage jar file
RUN mkdir -p target/dependency && (cd target/dependency; jar -xf /app.jar)

#stage 2
#Same Java runtime
FROM eclipse-temurin:21

#Add volume pointing to /tmp
VOLUME /tmp

#Copy unpackaged application to new container
#ARG DEPENDENCY=/target/dependency
COPY --from=build /target/dependency/BOOT-INF/lib /app/lib
COPY --from=build /target/dependency/META-INF /app/META-INF
COPY --from=build /target/dependency/BOOT-INF/classes /app

#execute the application
ENTRYPOINT ["java","-cp","app:app/lib/*","com.optimagrowth.license.LicenseServiceApplication"]