version: '3'

services:
  database:
    image: postgres
    ports:
      - "4523:4523"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
  organizationservice:
    image: ostock/organization-service:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
       - "SPRING_PROFILES_ACTIVE=dev"
    networks:
      backend:
        aliases:
          - "organizationservice"
networks:
  backend:
    driver: bridge